name: Deploy FastAPI + React App to GitHub

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  NODE_VERSION: "18"

jobs:
  backend:
    name: Build FastAPI Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r nestle-chatbot-backend/requirements.txt

      - name: Archive Backend
        run: |
          tar -czf backend.tar.gz nestle-chatbot-backend

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend.tar.gz

  frontend:
    name: Deploy React Frontend to GitHub Pages
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: nestle-chatbot-frontend
        run: npm install

      - name: Build React App
        working-directory: nestle-chatbot-frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: nestle-chatbot-frontend/dist
